# Generated by Django 4.1.8 on 2023-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
