# Generated by Django 4.1.8 on 2024-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0004_alter_opportunity_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="_search_field",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
