# Generated by Django 4.1.8 on 2024-01-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0013_opportunitypriority"),
        ("opportunities", "0005_opportunity__search_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="priority",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="categories.opportunitypriority",
            ),
        ),
    ]
