# Generated by Django 4.1.8 on 2024-01-18 10:13
from django.core.management import call_command
from django.db import migrations


def migrate(apps, schema_editor):
    Opportunity = apps.get_model("opportunities", "Opportunity")
    OpportunityPriority = apps.get_model("categories", "OpportunityPriority")
    call_command("create_categories")

    opportunities = []
    normal = OpportunityPriority.objects.get(slug="normal")
    for o in Opportunity.objects.all():
        o.priority = normal
        opportunities.append(o)

    Opportunity.objects.bulk_update(opportunities, ["priority"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0006_opportunity_priority"),
        ("other", "0005_donationpointsaggregation_donationpointscolumn_and_more"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
