# Generated by Django 4.1.8 on 2024-01-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0013_opportunitypriority"),
        ("opportunities", "0007_auto_20240118_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="priority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="categories.opportunitypriority",
            ),
        ),
    ]
