# Generated by Django 4.1.8 on 2023-09-21 10:16

import common.thumbnails
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0006_alter_brontosaurusmovement_audit_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='image',
            field=common.thumbnails.ThumbnailImageField(blank=True, upload_to='administration_unit_images'),
        ),
    ]
