# Generated by Django 4.1.8 on 2023-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0007_administrationunit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
