# Generated by Django 4.1.8 on 2023-12-06 12:19

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0008_alter_administrationunit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationSubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('is_for_kids', models.BooleanField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('www', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('gps_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('_history', models.JSONField(default=dict)),
                ('administration_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_units', to='administration_units.administrationunit')),
                ('main_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_leader_of', to=settings.AUTH_USER_MODEL)),
                ('sub_leaders', models.ManyToManyField(blank=True, related_name='sub_leader_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
