# Generated by Django 4.1.8 on 2023-12-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('administration_units', '0009_administrationsubunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrationsubunit',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='AdministrationSubUnitAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=127)),
                ('city', models.CharField(max_length=63)),
                ('zip_code', models.CharField(max_length=5)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region')),
                ('sub_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='administration_units.administrationsubunit')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
