# Generated by Django 4.1.8 on 2024-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administration_units",
            "0012_remove_administrationsubunit_existed_till_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="administrationunit",
            name="_search_field",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
