# Generated by Django 4.1.8 on 2025-12-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administration_units",
            "0014_administrationsubunit_administrat_name_adf09d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrationunit",
            options={"ordering": ("-existed_till", "abbreviation")},
        ),
        migrations.RemoveIndex(
            model_name="administrationunit",
            name="administrat_abbrevi_e5b92f_idx",
        ),
        migrations.AddIndex(
            model_name="administrationunit",
            index=models.Index(
                fields=["-existed_till", "abbreviation"],
                name="administrat_existed_ca13a7_idx",
            ),
        ),
    ]
