# Generated by Django 5.2.10 on 2026-04-27 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_units", "0015_alter_administrationunit_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brontosaurusmovement",
            name="fundraisers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mají přístup k telesales a vidí dárce",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
