# Generated by Django 4.0.10 on 2023-03-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0015_alter_event_is_canceled_alter_event_is_closed_and_more"),
        ("event", "0005_alter_eventpropagation_invitation_text_about_us_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vipeventpropagation",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vip_propagation",
                to="bis.event",
            ),
        ),
    ]
