# Generated by Django 4.0.10 on 2023-03-05 18:59

from django.db import migrations


def migrate(apps, schema_editor):
    VIPEventPropagation = apps.get_model('event', 'VIPEventPropagation')

    for p in VIPEventPropagation.objects.all():
        p.event = p.event_propagation.event
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0006_vipeventpropagation_event'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
