# Generated by Django 4.0.10 on 2023-03-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_vipeventpropagation_event_propagation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='attendance_list',
        ),
        migrations.CreateModel(
            name='EventAttendanceListPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(blank=True, null=True, upload_to='attendance_list_pages')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_list_pages', to='event.eventrecord')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
