# Generated by Django 4.0.10 on 2023-03-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_eventrecord_attendance_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpropagation',
            name='contact_person',
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='contact_name',
            field=models.CharField(help_text='Nechte prázdné pokud chcete použít jméno kontaktní osoby', max_length=63),
        ),
    ]
