# Generated by Django 4.1.8 on 2023-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_eventfinance_event_alter_eventrecord_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendancelistpage',
            name='page',
            field=models.FileField(blank=True, null=True, upload_to='attendance_list_pages'),
        ),
    ]
