# Generated by Django 4.1.8 on 2025-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0013_alter_eventattendancelistpage_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventrecord",
            name="number_of_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="U opakovaných akcí je nutné zadat celkový počet účastníků na všech akcích",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventrecord",
            name="number_of_participants_under_26",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="U opakovaných akcí je nutné zadat celkový počet účastníků na všech akcích",
                null=True,
            ),
        ),
    ]
