# Generated by Django 4.1.8 on 2025-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0014_alter_eventrecord_number_of_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrecord",
            name="is_event_closed_email_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
