# Generated by Django 5.2.10 on 2026-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0015_eventrecord_is_event_closed_email_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendancelistpage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
