# Generated by Django 5.2.10 on 2026-04-27 19:28

from django.db import migrations


def merge_record_note_into_event_internal_note(apps, schema_editor):
    EventRecord = apps.get_model("event", "EventRecord")
    for record in EventRecord.objects.exclude(note="").select_related("event"):
        event = record.event
        existing = event.internal_note or ""
        if existing:
            event.internal_note = existing.rstrip() + "\n\n" + record.note
        else:
            event.internal_note = record.note
        event.save(update_fields=["internal_note"])


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0018_make_upload_timestamps_required"),
    ]

    operations = [
        migrations.RunPython(
            merge_record_note_into_event_internal_note,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="eventrecord",
            name="note",
        ),
    ]
