# Generated by Django 5.2.10 on 2026-04-28 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0016_backfill_event_registration"),
        ("event", "0019_remove_eventrecord_note"),
    ]

    operations = []
