# Generated by Django 5.2.10 on 2026-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0021_move_section_event_to_section_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrecord",
            name="attendance_list_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full-list", "Plná prezenční listina"),
                    ("simple-list", "Zjednodušená prezenční listina"),
                    ("count", "Pouze počet účastníků"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
