# Generated by Django 5.2.10 on 2026-05-24 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0024_eventcontact_to_participants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventContact",
        ),
    ]
