# Generated by Django 3.2.17 on 2023-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0012_user_vokativ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="vokativ",
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
