# Generated by Django 4.1.8 on 2023-04-13 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0015_alter_event_is_canceled_alter_event_is_closed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("last_name",)},
        ),
    ]
