# Generated by Django 4.1.8 on 2023-09-27 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0016_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
