# Generated by Django 4.1.8 on 2023-10-23 11:32

from django.db import migrations

def migrate(apps, schema_editor):
    Event = apps.get_model('bis', 'Event')
    events = []
    for event in Event.objects.all():
        if event.start < event.created_at.date():
            event.created_at = event.start
            events.append(event)

    Event.objects.bulk_update(events, ["created_at"])

class Migration(migrations.Migration):
    dependencies = [
        ('bis', '0019_event_created_at'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
