# Generated by Django 4.1.8 on 2023-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0020_auto_20231023_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
