# Generated by Django 4.1.8 on 2023-10-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0021_alter_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Zarchivovaná akce nelze editovat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
