# Generated by Django 4.1.8 on 2023-10-24 07:50

from django.db import migrations


def migrate(apps, schema_editor):
    Event = apps.get_model('bis', 'Event')
    events = []
    for event in Event.objects.all():
        event.is_archived = event.is_closed
        events.append(event)

    Event.objects.bulk_update(events, ["is_archived"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ('bis', '0022_event_is_archived_alter_event_is_closed'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
