# Generated by Django 4.1.8 on 2023-10-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0023_auto_20231024_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_closed',
        ),
    ]
