# Generated by Django 4.1.8 on 2023-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_alter_eventprogramcategory_email'),
        ('bis', '0025_rename_is_complete_event_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='is_fully_specified',
            new_name='is_traditional',
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='categories.eventtag'),
        ),
    ]
