# Generated by Django 4.1.8 on 2023-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0026_rename_is_fully_specified_location_is_traditional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="closed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
