# Generated by Django 4.1.8 on 2023-12-18 11:19

from django.db import migrations

import common.thumbnails


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0029_qualificationnote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eycacard",
            name="photo",
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=common.thumbnails.ThumbnailImageField(
                blank=True, null=True, upload_to="user_photos"
            ),
        ),
    ]
