# Generated by Django 4.1.8 on 2024-01-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0031_auto_20231226_0938"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_after_event_email",
            field=models.DateField(blank=True, null=True),
        ),
    ]
