# Generated by Django 4.1.8 on 2024-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0032_user_last_after_event_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="created_at",
            field=models.DateField(null=True),
        ),
    ]
