# Generated by Django 4.1.8 on 2024-01-14 10:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0034_auto_20240114_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=datetime.date(1970, 1, 1)
            ),
            preserve_default=False,
        ),
    ]
