# Generated by Django 4.1.8 on 2024-01-17 12:07

import bis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0035_alter_membership_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"ordering": ("-year", "user__first_name", "user__last_name")},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("last_name", "first_name")},
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                help_text="Zde lze vyhledávat ve všech uživatelích BISu, ke kterým máte přístup",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="year",
            field=models.PositiveIntegerField(default=bis.models.this_year),
        ),
    ]
