# Generated by Django 4.1.8 on 2024-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0036_alter_membership_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_search_field",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
