# Generated by Django 4.1.8 on 2024-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0037_user__search_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_search_field",
            field=models.CharField(max_length=512),
        ),
    ]
