# Generated by Django 4.1.8 on 2024-01-18 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0038_alter_user__search_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="_search_field",
        ),
    ]
