# Generated by Django 4.1.8 on 2024-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0039_remove_user__search_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_search_field",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
