# Generated by Django 4.1.8 on 2024-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0040_user__search_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="_search_field",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="location",
            name="_search_field",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
