# Generated by Django 4.1.8 on 2024-01-18 09:08

from django.db import migrations
from unidecode import unidecode


def get_nested_attr(obj, fields):
    if len(fields) == 0:
        return obj
    obj = getattr(obj, fields[0], None) or ""
    return get_nested_attr(obj, fields[1:])


def get_search_field_value(instance, search_fields):
    return " ".join(
        unidecode(str(get_nested_attr(instance, field.split("__"))))
        for field in search_fields
    )[:1000]


def migrate(apps, schema_editor):
    models = [
        (
            apps.get_model("administration_units", "AdministrationUnit"),
            [
                "abbreviation",
                "name",
                "address__city",
                "address__street",
                "address__zip_code",
                "phone",
                "email",
            ],
        ),
        (
            apps.get_model("bis", "User"),
            [
                "all_emails__email",
                "phone",
                "first_name",
                "last_name",
                "nickname",
                "birth_name",
            ],
        ),
        (apps.get_model("bis", "Event"), ["name"]),
        (apps.get_model("bis", "Location"), ["name", "description"]),
        (apps.get_model("opportunities", "Opportunity"), ["name", "introduction"]),
    ]
    for model, search_fields in models:
        to_update = []
        for instance in model.objects.all():
            instance._search_field = get_search_field_value(instance, search_fields)
            to_update.append(instance)

        model.objects.bulk_update(to_update, ["_search_field"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0041_event__search_field_location__search_field"),
        ("opportunities", "0005_opportunity__search_field"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
