# Generated by Django 4.1.8 on 2024-02-18 17:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0043_alter_membership_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="created_at",
        ),
        migrations.AddField(
            model_name="membership",
            name="_year",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
