# Generated by Django 4.1.8 on 2024-02-18 17:06
from datetime import date

from django.db import migrations


def migrate(apps, schema_editor):
    Membership = apps.get_model("bis", "Membership")
    to_update = []
    for membership in Membership.objects.all():
        membership._year = date(membership.year, 1, 1)
        to_update.append(membership)

    Membership.objects.bulk_update(to_update, ["_year"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0044_remove_membership_created_at_membership__year"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
