# Generated by Django 4.1.8 on 2024-02-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0045_auto_20240218_1806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="_year",
            field=models.DateField(),
        ),
    ]
