# Generated by Django 4.1.8 on 2024-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0046_alter_membership__year"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start"], name="bis_event_start_9fc863_idx"),
        ),
    ]
