# Generated by Django 4.1.8 on 2024-02-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0047_event_bis_event_start_9fc863_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_name", "first_name"], name="bis_user_last_na_fd0cf0_idx"
            ),
        ),
    ]
