# Generated by Django 4.1.8 on 2024-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0048_user_bis_user_last_na_fd0cf0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_contact_information_verified",
            field=models.BooleanField(default=False),
        ),
    ]
