# Generated by Django 4.1.8 on 2024-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0049_user_is_contact_information_verified"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["name"], name="bis_locatio_name_632fdb_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["year"], name="bis_members_year_4bf18f_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["_year"], name="bis_members__year_9adf90_idx"),
        ),
    ]
