# Generated by Django 4.1.8 on 2025-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0050_location_bis_locatio_name_632fdb_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="behaviour_issues",
            field=models.TextField(
                blank=True,
                help_text="Pokud vyplněno, zobrazí se jako varování organizátorům akcí u přihlášky",
            ),
        ),
    ]
