# Generated by Django 4.2.27 on 2026-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0051_user_behaviour_issues"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "birthday"),
                name="unique_user_name_birthday",
            ),
        ),
    ]
