# Generated by Django 5.2.10 on 2026-04-27 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0052_alter_user_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="internal_note",
            new_name="office_workers_note",
        ),
    ]
