# Generated by Django 5.2.10 on 2026-04-27 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0053_rename_internal_note_user_office_workers_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qualificationnote",
            old_name="note",
            new_name="education_members_note",
        ),
    ]
