# Generated by Django 5.2.10 on 2026-04-27 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0054_rename_note_qualificationnote_education_members_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="internal_note",
            new_name="organizers_note",
        ),
    ]
