# Generated by Django 5.2.10 on 2026-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0055_rename_internal_note_event_organizers_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organizers_note",
            field=models.TextField(
                blank=True,
                help_text="Možnost přidat interní poznámku. Poznámku uvidí pouze lidé, kteří si mohou tuto akci zobrazit přímo v BISu.",
            ),
        ),
    ]
