# Generated by Django 5.2.10 on 2026-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0059_cleanup_invalid_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="_search_field",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
