env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - react-hooks
  - prettier
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  prettier/prettier: warn
  '@typescript-eslint/explicit-module-boundary-types': off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
settings:
  react:
    version: detect
