# Generated by Django 4.1.8 on 2026-01-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeCourse",
        ),
        migrations.DeleteModel(
            name="RecipeDietRestriction",
        ),
        migrations.DeleteModel(
            name="RecipeType",
        ),
        migrations.AddField(
            model_name="recipetag",
            name="group",
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
    ]
