# Generated by Django 4.1.8 on 2026-01-05 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0008_rename_time_required_recipe_required_time"),
        (
            "cookbook_categories",
            "0002_delete_recipecourse_delete_recipedietrestriction_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeTimeRequired",
            new_name="RecipeRequiredTime",
        ),
    ]
