# Generated by Django 4.1.8 on 2026-01-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0003_rename_recipetimerequired_reciperequiredtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31)),
                ("slug", models.SlugField()),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "of",
                    models.CharField(
                        choices=[
                            ("weight", "Váha"),
                            ("volume", "Objem"),
                            ("pieces", "Kus"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
