# Generated by Django 4.1.8 on 2026-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0004_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="name2",
            field=models.CharField(default=None, max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unit",
            name="name5",
            field=models.CharField(default=None, max_length=31),
            preserve_default=False,
        ),
    ]
