# Generated by Django 4.1.8 on 2026-01-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0005_unit_name2_unit_name5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="of",
            field=models.CharField(
                choices=[
                    ("weight", "Váha"),
                    ("volume", "Objem"),
                    ("pieces", "Kus"),
                    ("servings", "Porce"),
                ],
                max_length=15,
            ),
        ),
    ]
