# Generated by Django 4.1.8 on 2026-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0006_alter_unit_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
