# Generated by Django 4.1.8 on 2026-01-06 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0008_recipedifficulty_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipedifficulty",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recipedifficulty",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="recipedifficulty",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="recipedifficulty",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="reciperequiredtime",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reciperequiredtime",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reciperequiredtime",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="reciperequiredtime",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="updated_by",
        ),
    ]
