# Generated by Django 5.2.10 on 2026-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0009_remove_recipedifficulty_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31)),
                ("slug", models.SlugField()),
                ("order", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
