#!/usr/bin/env python3
"""Generate frontend/src/config/static/translations.ts from the yaml sources.

Run automatically by pre-commit whenever model_translations.yaml or
string_translations.yaml changes. The output is then reformatted by the
prettier pre-commit hook.

To avoid fighting prettier on every run, the script embeds a hash of the
source yamls in the generated file and skips rewriting when the hash
already matches.
"""

import hashlib
import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
MODEL_YAML = HERE / "model_translations.yaml"
STRING_YAML = HERE / "string_translations.yaml"
OUTPUT = REPO_ROOT / "frontend" / "src" / "config" / "static" / "translations.ts"


def lower_first(name: str) -> str:
    return name[:1].lower() + name[1:] if name else name


def dump(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    model_bytes = MODEL_YAML.read_bytes()
    string_bytes = STRING_YAML.read_bytes()
    source_hash = hashlib.sha256(model_bytes + b"\x00" + string_bytes).hexdigest()[:16]
    hash_marker = f"source-hash: {source_hash}"

    if OUTPUT.exists() and hash_marker in OUTPUT.read_text(encoding="utf-8"):
        return

    header = (
        "// This file was automatically generated by a pre-commit hook.\n"
        "//\n"
        "// !!!DO NOT EDIT!!!\n"
        "//\n"
        "// It is regenerated from backend/translation/{model,string}_translations.yaml\n"
        "// by backend/translation/generate_translations.py whenever the yamls change.\n"
        f"// {hash_marker}\n"
        "\n\n"
    )

    model_translations = yaml.safe_load(model_bytes)
    string_translations = yaml.safe_load(string_bytes)

    entries: list[tuple[str, dict]] = []

    for raw_name, raw in model_translations.items():
        fields = raw.get("fields") or {}
        # Note: _name_plural intentionally mirrors _name to match the prior
        # TypeScript generator's behavior. Fix separately if desired.
        model = {"_name": raw["name"], "_name_plural": raw["name"], **fields}
        entries.append((lower_first(raw_name), model))

    for name, value in string_translations.items():
        entries.append((name, value))

    body = "".join(
        f"export const {name} = {dump(value)} as const;\n\n" for name, value in entries
    )

    OUTPUT.write_text(header + body, encoding="utf-8")


if __name__ == "__main__":
    main()
