# Generated by Django 4.1.8 on 2023-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_book', '0010_alter_game_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
