# Generated by Django 4.1.8 on 2023-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_book', '0012_alter_game_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Zobrazit komentář pouze autorovi?'),
        ),
    ]
