# Generated by Django 4.1.8 on 2023-12-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlog",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
