# Generated by Django 4.1.8 on 2023-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_rename_sexcategory_pronouncategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipcategory",
            name="price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
