# Generated by Django 4.1.8 on 2023-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0005_membershipcategory_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipcategory",
            name="price",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
