# Generated by Django 4.1.8 on 2023-10-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_eventtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Neaktivní tagy se nezobrazí organizátorovi při vytváření nové akce'),
        ),
    ]
