# Generated by Django 4.1.8 on 2023-10-23 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0009_eventprogramcategory_notification_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventprogramcategory",
            old_name="notification_email",
            new_name="email",
        ),
    ]
