# Generated by Django 4.1.8 on 2024-03-17 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0014_alter_eventcategory_options_eventcategory_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershipcategory",
            name="price",
        ),
    ]
