# Generated by Django 4.1.8 on 2025-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0015_remove_membershipcategory_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcategory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
