version: '3'
services:
  backend:
    environment:
      TEST: 1
      ALLOWED_HOSTS: '*'

  postgres:
    volumes:
      - postgresqldata_test:/var/lib/postgresql/data

volumes:
  postgresqldata_test:
    external: true
