version: '3'
services:
  backend:
    environment:
      TEST: 1
      ALLOWED_HOSTS: '*'
      FULL_HOSTNAME: 'http://localhost'

  postgres:
    volumes:
      - ./postgresqldata_test:/var/lib/postgresql/data
