# Generated by Django 4.1.8 on 2023-12-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="official_vokativ",
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
