# Generated by Django 4.1.8 on 2023-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0002_donor_official_vokativ"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="official_vokativ",
        ),
        migrations.AddField(
            model_name="donor",
            name="formal_vokativ",
            field=models.CharField(
                blank=True, help_text="Pro účely potvrzení o daru", max_length=63
            ),
        ),
    ]
