# Generated by Django 4.1.8 on 2023-12-12 11:38

from django.db import migrations
from vokativ import vokativ


def migrate(apps, schema_editor):
    Donor = apps.get_model("donations", "Donor")
    donors = []
    for donor in Donor.objects.all():
        donor.formal_vokativ = vokativ(donor.user.last_name.split(" ")[0]).capitalize()
        donors.append(donor)

    Donor.objects.bulk_update(donors, ["formal_vokativ"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_remove_donor_official_vokativ_donor_formal_vokativ"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
