# Generated by Django 4.1.8 on 2026-01-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0017_donoreventcategory"),
        ("donations", "0004_auto_20231212_1238"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="has_recurrent_donation",
        ),
        migrations.CreateModel(
            name="Pledge",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("is_recurrent", models.BooleanField(default=False)),
                (
                    "recurrent_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("one_time", "One Time"),
                            ("stopped", "Stopped"),
                            ("collecting", "Collecting"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("pledged_at", models.DateTimeField()),
                (
                    "donation_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pledges",
                        to="categories.donationsourcecategory",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pledges",
                        to="donations.donor",
                    ),
                ),
            ],
            options={
                "ordering": ("-pledged_at",),
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="pledge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="donations.pledge",
            ),
        ),
        migrations.CreateModel(
            name="DonorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_sent_at", models.DateTimeField()),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.donor",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="categories.donoreventcategory",
                    ),
                ),
                (
                    "pledge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.pledge",
                    ),
                ),
            ],
            options={
                "unique_together": {("donor", "pledge", "event_type")},
            },
        ),
    ]
