# Generated by Django 5.2.10 on 2026-03-16 08:52
from datetime import timedelta

from dateutil.relativedelta import relativedelta
from django.db import migrations
from django.db.models import Count, Max, Q, Sum
from django.utils import timezone


def backfill_donorevent(apps, schema_editor):
    Donor = apps.get_model("donations", "Donor")
    DonorEvent = apps.get_model("donations", "DonorEvent")
    DonorEventCategory = apps.get_model("categories", "DonorEventCategory")

    now = timezone.now()
    today = now.date()

    def bulk_create_donor_event(donors, event_type):
        DonorEvent.objects.bulk_create(
            [
                DonorEvent(
                    donor=donor,
                    event_type=event_type,
                    email_sent_at=now,
                )
                for donor in donors
            ]
        )

    # 1. recurrent_donor_stopped
    event_type = DonorEventCategory.objects.get(slug="recurrent_stopped")

    donors = Donor.objects.annotate(
        times_donated=Count(
            "donations",
            filter=Q(donations__pledge__is_recurrent=True),
            distinct=True,
        ),
        last_donation_date=Max(
            "donations__donated_at", filter=Q(donations__pledge__is_recurrent=True)
        ),
    ).filter(
        pledges__is_recurrent=True,
        times_donated__gte=2,
        last_donation_date__lt=today - relativedelta(months=2),
    )
    bulk_create_donor_event(donors, event_type)

    # 2. new_recurrent_donors
    event_type = DonorEventCategory.objects.get(slug="new_recurrent_pledge")
    donors = Donor.objects.filter(
        pledges__is_recurrent=True,
        pledges__recurrent_state="collecting",
        pledges__pledged_at=today - timedelta(days=2),
    ).exclude(donorevent__event_type=event_type)
    bulk_create_donor_event(donors, event_type)

    # 3. donated_10k
    event_type = DonorEventCategory.objects.get(slug="donor_10k_total")

    donors = (
        Donor.objects.annotate(total_donated=Sum("donations__amount"))
        .filter(total_donated__gte=10000)
        .exclude(donorevent__event_type=event_type)
    )
    bulk_create_donor_event(donors, event_type)

    # 4. donates_for_years
    years = [5, 4, 3, 2, 1]

    for year in years:
        event_type = DonorEventCategory.objects.get(slug=f"pledge_{year}y")

        cutoff = today - relativedelta(years=year)

        donors = (
            Donor.objects.filter(
                pledges__is_recurrent=True,
                pledges__recurrent_state="collecting",
                pledges__pledged_at__lte=cutoff,
            )
            .exclude(donorevent__event_type__slug__icontains="pledge_")
            .distinct()
        )
        bulk_create_donor_event(donors, event_type)


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0005_remove_donor_has_recurrent_donation_pledge_and_more"),
    ]

    operations = [migrations.RunPython(backfill_donorevent)]
