# Generated by Django 5.2.10 on 2026-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0005_remove_donor_has_recurrent_donation_pledge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pledge",
            name="pledged_at",
            field=models.DateField(),
        ),
    ]
