# Generated by Django 5.2.10 on 2026-03-16 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0006_backfill_donor_events"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="donorevent",
            unique_together=set(),
        ),
    ]
