# Generated by Django 5.2.10 on 2026-03-23 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0006_backfill_donor_events"),
    ]

    operations = [
        # Migration 0005 was edited after being applied to prod. Fix the three resulting
        # schema inconsistencies between prod and the current migration state:
        # 1. unique_together was (donor, pledge, event_type) in prod, not (donor, event_type)
        # 2. DonorEvent had a pledge FK in prod that was removed without a migration
        # 3. Pledge.pledged_at was DateTimeField in prod, changed to DateField without a migration
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        DECLARE r record;
                        BEGIN
                            FOR r IN (
                                SELECT con.conname
                                FROM pg_constraint con
                                JOIN pg_class rel ON rel.oid = con.conrelid
                                WHERE rel.relname = 'donations_donorevent' AND con.contype = 'u'
                            )
                            LOOP
                                EXECUTE 'ALTER TABLE donations_donorevent DROP CONSTRAINT IF EXISTS "' || r.conname || '"';
                            END LOOP;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE donations_donorevent DROP COLUMN IF EXISTS pledge_id",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE donations_pledge ALTER COLUMN pledged_at TYPE date USING pledged_at::date",
                    reverse_sql="ALTER TABLE donations_pledge ALTER COLUMN pledged_at TYPE timestamp with time zone USING pledged_at::timestamptz",
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="donorevent",
                    unique_together=set(),
                ),
            ],
        ),
    ]
