# Generated by Django 5.2.10 on 2026-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0012_move_fundraising_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="donorevent",
            name="prislib",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="donorevent",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
