# Generated by Django 5.2.10 on 2026-04-21 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0013_donorevent_prislib_reminder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donorevent",
            old_name="prislib",
            new_name="pledge",
        ),
    ]
