# Generated by Django 5.2.10 on 2026-04-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0015_donor_do_not_call_do_not_solicit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ico", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=255)),
                (
                    "donor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="donations.donor",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
