# Generated by Django 5.2.10 on 2026-04-27 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0016_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donor",
            old_name="internal_note",
            new_name="fundraisers_note",
        ),
        migrations.RenameField(
            model_name="donorevent",
            old_name="note",
            new_name="fundraisers_note",
        ),
    ]
