# Generated by Django 5.2.10 on 2026-05-25 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_units", "0016_brontosaurusmovement_fundraisers"),
        ("categories", "0019_remove_fundraisingcampaigncategory"),
        ("donations", "0019_merge_call_declined_into_call_no_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donated_at"], name="donations_d_donated_7b0c04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(
                fields=["date_joined"], name="donations_d_date_jo_1f0621_idx"
            ),
        ),
    ]
