# Generated by Django 4.0.10 on 2023-03-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0002_feedback_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateuser',
            name='other',
            field=models.ForeignKey(help_text='Tento uživatel (by měl) být zastaralý, jeho informace budou (po kontrole) připojeny k primárnímu (vybranému) uživateli', on_delete=django.db.models.deletion.CASCADE, related_name='other_duplicates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duplicateuser',
            name='user',
            field=models.ForeignKey(help_text='Tento uživatel (by měl) obsahovat aktuání informace', on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to=settings.AUTH_USER_MODEL),
        ),
    ]
