# Generated by Django 4.1.8 on 2024-01-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0004_alter_feedback_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationPointsAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="DonationPointsColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_per_each", models.PositiveSmallIntegerField()),
                (
                    "aggregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="other.donationpointsaggregation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationPointsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "columns",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="other.donationpointscolumn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "since",
                    models.DateField(
                        help_text="Filtruji akce které začaly po daném datumu"
                    ),
                ),
                (
                    "till",
                    models.DateField(
                        help_text="Filtruji akce které začaly do daného datumu, filtruji členství za rok kterému patří tento den, určuji stáří členů k tomuto datu"
                    ),
                ),
                (
                    "sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="other.donationpointssection",
                    ),
                ),
            ],
        ),
    ]
