# Generated by Django 4.1.8 on 2024-01-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0006_remove_donationpoints_sections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpointscolumn",
            name="points_per_each",
            field=models.FloatField(),
        ),
    ]
