# Generated by Django 4.1.8 on 2024-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0009_delete_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationpoints",
            name="name",
            field=models.CharField(default="Body dotací", max_length=255),
            preserve_default=False,
        ),
    ]
