# Generated by Django 4.1.8 on 2025-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0010_donationpoints_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("file", models.FileField(upload_to="saved_files")),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
