# Generated by Django 4.1.8 on 2025-05-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0011_savedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarditem",
            name="visible_date",
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
