# Generated by Django 4.1.8 on 2025-05-29 08:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0012_dashboarditem_visible_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboarditem",
            name="description",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="dashboarditem",
            name="name",
            field=tinymce.models.HTMLField(max_length=63),
        ),
        migrations.AlterField(
            model_name="dashboarditem",
            name="visible_date",
            field=tinymce.models.HTMLField(blank=True, max_length=63),
        ),
    ]
