# Generated by Django 4.2.27 on 2026-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0013_alter_dashboarditem_description_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="duplicateuser",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="duplicateuser",
            constraint=models.UniqueConstraint(
                fields=("user", "other"), name="unique_duplicate_user_pair"
            ),
        ),
    ]
