# Generated by Django 5.2.10 on 2026-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0014_alter_duplicateuser_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Varování"),
                            ("error", "Chyba"),
                        ],
                        default="info",
                        max_length=7,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
            options={
                "ordering": ("-start",),
            },
        ),
    ]
