# Generated by Django 5.2.10 on 2026-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0019_remove_fundraisingcampaigncategory"),
        ("other", "0016_remove_any_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboarditem",
            name="for_roles",
            field=models.ManyToManyField(
                help_text="Pokud nezvolíš žádnou roli, termín uvidí všichni uživatelé.",
                related_name="dashboard_items",
                to="categories.rolecategory",
            ),
        ),
    ]
