# Generated by Django 5.2.10 on 2026-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0019_remove_fundraisingcampaigncategory"),
        ("other", "0018_usertag"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="for_roles",
            field=models.ManyToManyField(
                help_text="Pokud nezvolíš žádnou roli, oznámení uvidí všichni uživatelé.",
                related_name="announcements",
                to="categories.rolecategory",
            ),
        ),
    ]
