# Generated by Django 5.2.10 on 2026-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other", "0019_announcement_for_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
