# Generated by Django 3.2.17 on 2023-02-26 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0004_auto_20230128_2118"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventapplication",
            old_name="sex",
            new_name="pronoun",
        ),
    ]
