# Generated by Django 4.0.10 on 2023-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_rename_sex_eventapplication_pronoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='child_application',
            field=models.BooleanField(default=False),
        ),
    ]
