# Generated by Django 4.1.8 on 2024-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0008_alter_eventapplication_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventapplication",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
    ]
