# Generated by Django 4.1.8 on 2024-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0009_eventapplication_internal_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventapplication",
            name="paid_for",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventapplication",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Čeká na schválení"),
                    ("queued", "Náhradník"),
                    ("cancelled", "Zrušena"),
                    ("rejected", "Zamítnuta"),
                    ("approved", "Potvrzena"),
                ],
                max_length=15,
            ),
        ),
    ]
