# Generated by Django 5.2.10 on 2026-04-27 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0010_eventapplication_paid_for_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventapplication",
            name="internal_note",
        ),
    ]
