# Generated by Django 5.2.10 on 2026-04-27 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0011_remove_eventapplication_internal_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventapplication",
            old_name="note",
            new_name="applicant_note",
        ),
    ]
