# Generated by Django 4.1.8 on 2025-12-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
