# Generated by Django 4.1.8 on 2025-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0002_recipe_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="cookbook.recipetag"
            ),
        ),
    ]
