# Generated by Django 4.1.8 on 2025-12-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0003_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="recipestep",
            options={"ordering": ("order",)},
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="is_optional",
        ),
        migrations.RemoveField(
            model_name="recipestep",
            name="is_optional",
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
