# Generated by Django 4.1.8 on 2026-01-02 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0004_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.DeleteModel(
            name="RecipeDifficulty",
        ),
        migrations.DeleteModel(
            name="RecipeTag",
        ),
    ]
