# Generated by Django 4.1.8 on 2026-01-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0001_initial"),
        ("cookbook", "0005_remove_recipe_difficulty_remove_recipe_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="cookbook_categories.recipedifficulty",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="cookbook_categories.recipetag"
            ),
        ),
    ]
