# Generated by Django 4.1.8 on 2026-01-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cookbook_categories",
            "0002_delete_recipecourse_delete_recipedietrestriction_and_more",
        ),
        ("cookbook", "0006_recipe_difficulty_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="time_required",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="cookbook_categories.recipetimerequired",
            ),
            preserve_default=False,
        ),
    ]
