# Generated by Django 4.1.8 on 2026-01-05 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0007_recipe_time_required"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="time_required",
            new_name="required_time",
        ),
    ]
