# Generated by Django 4.1.8 on 2026-01-05 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0008_rename_time_required_recipe_required_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipestep",
            name="is_required",
        ),
    ]
