# Generated by Django 4.1.8 on 2026-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0009_remove_recipestep_is_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="g_per_serving",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
