# Generated by Django 4.1.8 on 2026-01-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook_categories", "0007_unit_abbreviation"),
        ("cookbook", "0010_ingredient_g_per_serving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menurecipeingredient",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_recipe_ingredients",
                to="cookbook_categories.unit",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_ingredients",
                to="cookbook_categories.unit",
            ),
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
