# Generated by Django 4.1.8 on 2026-01-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0013_alter_chef_options_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="reasoning",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="state",
            field=models.CharField(
                choices=[("solid", "Pevná"), ("liquid", "Tekuté")],
                default="solid",
                max_length=13,
            ),
        ),
    ]
