# Generated by Django 4.1.8 on 2026-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0014_ingredient_reasoning_alter_ingredient_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
