# Generated by Django 4.1.8 on 2026-01-07 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cookbook", "0015_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipecomment",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="cookbook.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="cookbook.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="cookbook.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipetip",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tips",
                to="cookbook.recipe",
            ),
        ),
    ]
