# Generated by Django 5.2.10 on 2026-02-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cookbook",
            "0016_alter_recipecomment_recipe_alter_recipecomment_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="menurecipeingredient",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.FloatField(),
        ),
    ]
