# Generated by Django 5.2.10 on 2026-05-02 19:54

import common.thumbnails
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0017_alter_menurecipeingredient_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="intro",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=common.thumbnails.ThumbnailImageField(
                blank=True, upload_to="recipes"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="sources",
            field=models.TextField(blank=True),
        ),
    ]
