# Generated by Django 5.2.10 on 2026-05-02 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0018_alter_recipe_intro_alter_recipe_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chef",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ("-id",)},
        ),
    ]
