# Generated by Django 5.2.10 on 2026-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0019_alter_chef_options_alter_ingredient_options_and_more"),
        ("cookbook_categories", "0010_allergen"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="allergens",
            field=models.ManyToManyField(
                blank=True,
                related_name="ingredients",
                to="cookbook_categories.allergen",
            ),
        ),
    ]
