# Generated by Django 5.2.10 on 2026-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0020_ingredient_allergens"),
        ("cookbook_categories", "0010_allergen"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="allergens",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="cookbook_categories.allergen"
            ),
        ),
    ]
