# Generated by Django 5.2.10 on 2026-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0021_recipe_allergens"),
    ]

    operations = [
        migrations.AddField(
            model_name="chef",
            name="cart",
            field=models.JSONField(default=list),
        ),
    ]
