# Generated by Django 5.2.10 on 2026-05-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0024_is_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="state",
            field=models.CharField(
                choices=[("solid", "Pevné"), ("liquid", "Tekuté")],
                default="solid",
                max_length=13,
            ),
        ),
    ]
