# Generated by Django 5.2.10 on 2026-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0029_categorize_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="other_items",
            field=models.JSONField(default=list),
        ),
    ]
