# Generated by Django 5.2.10 on 2026-09-30 09:01

import cookbook.models.ingredients
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0031_uncategorized_ingredients_to_other"),
        ("cookbook_categories", "0011_ingredientcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.ForeignKey(
                default=cookbook.models.ingredients.other_category_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingredients",
                to="cookbook_categories.ingredientcategory",
            ),
        ),
    ]
