# Generated by Django 4.1.8 on 2024-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfeedback",
            name="name",
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
