# Generated by Django 4.1.8 on 2025-09-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_alter_eventfeedback_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
