# Generated by Django 4.1.8 on 2025-11-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0051_user_behaviour_issues"),
        ("feedback", "0003_inquiry_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfeedback",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_feedbacks",
                to="bis.event",
            ),
        ),
        migrations.AddField(
            model_name="feedbackform",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_feedback_form",
                to="bis.event",
            ),
        ),
    ]
