# Generated by Django 4.1.8 on 2025-11-01 17:10

from django.db import migrations


def migrate(apps, schema_editor):
    FeedbackForm = apps.get_model("feedback", "FeedbackForm")
    EventFeedback = apps.get_model("feedback", "EventFeedback")
    feedbacks = []
    feedback_forms = []
    for feedback in EventFeedback.objects.all():
        feedback.event_id = feedback.event_record.event_id
        feedbacks.append(feedback)

    for feedback in FeedbackForm.objects.all():
        feedback.event_id = feedback.event_record.event_id
        feedback_forms.append(feedback)

    EventFeedback.objects.bulk_update(feedbacks, ["event_id"], batch_size=100)
    FeedbackForm.objects.bulk_update(feedback_forms, ["event_id"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_eventfeedback_event_feedbackform_event"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
