# Generated by Django 4.1.8 on 2025-11-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0051_user_behaviour_issues"),
        ("feedback", "0005_auto_20251101_1810"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventfeedback",
            name="event_record",
        ),
        migrations.RemoveField(
            model_name="feedbackform",
            name="event_record",
        ),
        migrations.AlterField(
            model_name="eventfeedback",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedbacks",
                to="bis.event",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedback_form",
                to="bis.event",
            ),
        ),
    ]
