# Generated by Django 4.1.8 on 2025-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_remove_eventfeedback_event_record_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackform",
            name="sent_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
