# Generated by Django 4.1.8 on 2025-11-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0051_user_behaviour_issues"),
        ("feedback", "0007_feedbackform_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackform",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedback_form",
                to="bis.event",
            ),
        ),
    ]
