# Generated by Django 4.1.8 on 2025-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0008_alter_feedbackform_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="value",
            field=models.JSONField(default=None, null=True),
        ),
    ]
