# Generated by Django 4.1.8 on 2025-12-01 10:41

from django.db import migrations


def migrate(apps, schema_editor):
    Reply = apps.get_model("feedback", "Reply")
    replies = []
    for reply in Reply.objects.all():
        if reply.inquiry.data["type"] in ["radio", "checkbox"]:
            reply.value = [
                option["option"]
                for option in reply.inquiry.data["options"]
                if option["option"] in reply.reply
            ]

        elif reply.inquiry.data["type"] == "scale":
            value = reply.data.get("rating", reply.reply)
            try:
                reply.value = int(value)
            except (TypeError, ValueError):
                pass

        replies.append(reply)

    Reply.objects.bulk_update(replies, ["value"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0009_reply_value"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
