# Generated by Django 4.1.8 on 2025-12-02 12:42

from django.db import migrations


def migrate(apps, schema_editor):
    Inquiry = apps.get_model("feedback", "Inquiry")
    items = []
    for item in Inquiry.objects.all():
        item.slug = {
            "Anketka": "check_in_section_heading",
            "Pokolikáté jsi na akci s Hnutí Brontosaurus? (myslíme tábor nebo víkendovou akci)": "previous_participation_number",
            "Dozvěděl/a ses nejdříve o této akci nebo o Hnutí Brontosaurus jako celku?": "previous_brontosaurus_knowledge",
            "Dozvěděl/a  ses nejdříve o této akci nebo o Hnutí Brontosaurus jako celku?": "previous_brontosaurus_knowledge",
            "Jak ses dozvěděl/a o této akci?": "propagation_source",
            "Jak ses dozvěděl/a o tomto táboře?": "propagation_source",
            "Podle čeho sis vybral/a tuto akci? Prosím vyber pro tebe nejdůležitější 3 důvody": "participation_reasons",
            "Chceš nám napsat něco více k tomu, proč sis vybral/a tuto akci? Budeme rádi za jakýkoli komentář": "participation_reasons_comment",
            "O akci": "event_section_heading",
            "Komunikace před akcí byla jasná a měl/a jsem dostatek informací ": "pre_event_communication",
            "Komunikace před akcí byla jasná a měl/a jsem dostatek informací": "pre_event_communication",
            "Věděl/a jsem, že akce je součástí neziskové organizace Hnutí Brontosaurus a byly mi poskytnuty informace o tom, jaké akce Hnutí Brontosaurus pořádá.": "brontosaurus_communication",
            "Na akci jsem se cítil/a bezpečně a měl/a jsem se na koho v případě potřeby obrátit.": "event_safety",
            "Zázemí (ubytování, jídlo…) odpovídalo tomu, co bylo na akci inzerováno.": "facilities_information_veracity",
            "Náplň akce mi přišla pestrá, zajímavá a dobře připravená": "event_program",
            "Přístup organizátorů k účastníkům byl milý, nápomocný a upřímný.": "organizer_attitude",
            "Dobrovolnická činnost": "volunteering_section_heading",
            "Měl/a jsem dostatek informací o účelu a smysluplnosti dobrovolnické činnosti.": "volunteering_communication",
            "Já osobně jsem považoval/a dobrovolnickou činnost za smysluplnou a cítil/a jsem, že pomáhám přírodě, památkám nebo lidem.": "volunteering_meaningfulness",
            "Dobrovolnická činnost byla přiměřeně náročná s dostatkem času na odpočinek.": "volunteering_difficulty",
            "Dobrovolnickou činnost jsem si užil/a a bavila mě - pomůže nám, když nám napíšeš, co konkrétně tě na práci nejvíce bavilo a proč ti přišla užitečná.": "volunteering_fun",
            "Atmosféra": "atmosphere_section_heading",
            "Díky účasti na akci jsem si rozšířil/a obzory nebo získal/a nový pohled na to jak vnímám své okolí a okolní přírodu": "impact_self",
            "Na akci jsem se seznámil/a s lidmi, s kterými bych rád/a dál udržovala kontakt i po akci": "impact_people",
            "Jak hodnotíš celkovou atmosféru na akci? Co konkrétně se ti na akci líbilo a co bys rád/a vylepšil/a? Tvoje zpětná vazba nám umožní se stále zlepšovat.": "event_atmosphere",
            "Zapojení": "involvement_section_heading",
            "Chceš se více zapojit do činnosti Hnutí Brontosaurus? Rádi ti s tím pomůžeme a přivítáme tě mezi sebou :) Co tě nejvíc láká? Možnosti jak se zapojit najdeš i na webu Zapoj se": "involvement_means",
            "Poskytuje Hnutí Brontosaurus dostatek příležitostí, jak se zapojit? Jakým způsobem ti HB může pomoci, aby jsi udržel/a vzniklá přátelství a více se zapojil/a do činnosti HB (organizace táborů a další akce)": "involvement_feedback",
        }.get(item.inquiry) or ""
        items.append(item)

    Inquiry.objects.bulk_update(items, ["slug"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0010_auto_20251201_1141"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
