# Generated by Django 5.2.10 on 2026-02-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bis", "0052_alter_user_unique_together_and_more"),
        ("feedback", "0011_auto_20251202_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackform",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_form",
                to="bis.event",
            ),
        ),
    ]
