# Generated by Django 5.2.10 on 2026-02-04 12:53

import contextlib

from django.db import migrations


def migrate(apps, schema_editor):
    Reply = apps.get_model("feedback", "Reply")
    replies = []
    for reply in Reply.objects.all():
        if reply.inquiry.data["type"] in ["radio", "checkbox"]:
            reply.value = [
                option["option"]
                for option in reply.inquiry.data["options"]
                if option["option"] in reply.reply
            ]

        elif reply.inquiry.data["type"] == "scale":
            value = reply.data.get("rating", reply.reply)
            with contextlib.suppress(TypeError, ValueError):
                reply.value = int(value)

        replies.append(reply)

    Reply.objects.bulk_update(replies, ["value"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0012_alter_feedbackform_event"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
