# Generated by Django 5.2.10 on 2026-04-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0013_auto_20260204_1353"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackform",
            name="email_content",
            field=models.TextField(blank=True),
        ),
    ]
