# Generated by Django 5.2.10 on 2026-04-27 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0014_feedbackform_email_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventfeedback",
            name="note",
        ),
    ]
