# Generated by Django 5.2.10 on 2026-05-05 13:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0016_feedbackform_email_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackform",
            name="email_content",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="email_subject",
            field=models.CharField(max_length=255),
        ),
    ]
